# Generated by Django 5.0.2 on 2024-07-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='relationship',
        ),
    ]
